services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    volumes:
      - ..:/workspaces/qrcodebook:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: qrcodebook
      POSTGRES_DB: qrcodebook
      POSTGRES_PASSWORD: qrcodebook

volumes:
  postgres-data:
